project:
  type: website

execute-dir: project

website:
  title: "prophecy.engineer"

  navbar:
    left:
      # - text: Home
      #   href: index.qmd
      - text: About
        href: about.qmd
      - text: Blog
        href: blog/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
