project:
  type: website

execute-dir: project

website:
  title: "prophecy.institute"

  navbar:
    left:
      - text: Learning Journey
        href: learning-journey/index.qmd
      - text: Roadmap
        href: roadmap/index.qmd
      - text: Resources
        href: resources.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Papers
        href: papers.qmd
      - text: Bookshelf
        href: books.qmd
      - text: Courses
        href: courses.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
