project:
  type: website

execute-dir: project

website:
  title: "charlotteai.engineer"

  navbar:
    left:
      - text: Learning Journey
        href: learning-journey/index.qmd
      - text: Resources
        href: resources.qmd
      - text: Blog
        href: blog/index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
