project:
  type: website

execute-dir: project

website:
  title: "charlotteai.engineer"

  navbar:
    left:
      - text: Learning Journey
        href: learning-journey/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
